const Enumeration = {
  ACCESS_TOKEN_EXPIRY: 'ACCESS_TOKEN_EXPIRY',
  ACCESS_TOKEN_SECRET: 'ACCESS_TOKEN_SECRET',
  PORT: 'PORT',
  REFRESH_TOKEN_EXPIRY: 'REFRESH_TOKEN_EXPIRY',
  REFRESH_TOKEN_SECRET: 'REFRESH_TOKEN_SECRET',
};

export { Enumeration };
