const Enumeration = {
  ACCESS_TOKEN_EXPIRY: 'ACCESS_TOKEN_EXPIRY',
  ACCESS_TOKEN_SECRET: 'ACCESS_TOKEN_SECRET',
  CAPTCHA_SECRET: 'CAPTCHA_SECRET',
  DB_CONNECTION: 'DB_CONNECTION',
  DB_SCHEMA: 'DB_SCHEMA',
  DEBUG: 'DEBUG',
  NODE_ENV: 'NODE_ENV',
  PASSWORD_RESET_EMAIL_FROM_ADDRESS: 'PASSWORD_RESET_EMAIL_FROM_ADDRESS',
  PASSWORD_RESET_EMAIL_FROM_NAME: 'PASSWORD_RESET_EMAIL_FROM_NAME',
  PORT: 'PORT',
  REFRESH_TOKEN_EXPIRY: 'REFRESH_TOKEN_EXPIRY',
  REFRESH_TOKEN_SECRET: 'REFRESH_TOKEN_SECRET',
  SMTP_CONNECTION: 'SMTP_CONNECTION',
  UI_HOST_URI: 'UI_HOST_URI',
};

export { Enumeration };
