const values = [
  'ACCESS_TOKEN_EXPIRY',
  'ACCESS_TOKEN_SECRET',
  'CAPTCHA_SECRET',
  'DATABASE_URL',
  'DB_MIGRATION_SCHEMA',
  'DB_MIGRATION_TABLE_NAME',
  'DB_SCHEMA',
  'DEBUG',
  'HTTPS',
  'NODE_ENV',
  'npm_package_name',
  'PASSWORD_RESET_EMAIL_FROM_ADDRESS',
  'PASSWORD_RESET_EMAIL_FROM_NAME',
  'PORT',
  'REFRESH_TOKEN_EXPIRY',
  'REFRESH_TOKEN_SECRET',
  'SMTP_CONNECTION',
  'UI_HOST_URI',
];

export { values };
