const Enumeration = {
  ACCESS_TOKEN_EXPIRY: 'ACCESS_TOKEN_EXPIRY',
  ACCESS_TOKEN_SECRET: 'ACCESS_TOKEN_SECRET',
  DB_CONNECTION: 'DB_CONNECTION',
  DB_SCHEMA: 'DB_SCHEMA',
  PORT: 'PORT',
  REFRESH_TOKEN_EXPIRY: 'REFRESH_TOKEN_EXPIRY',
  REFRESH_TOKEN_SECRET: 'REFRESH_TOKEN_SECRET',
};

export { Enumeration };
