const BASE_UNIT = 1;

// All units are rem
export const Layout = {
  BASE_UNIT,
  HEADER_HEIGHT: BASE_UNIT * 2.75,
  MAIN_BREADCRUMB_HEIGHT: BASE_UNIT * 2,
  MAIN_FOOTER_HEIGHT: BASE_UNIT * 2.25,
  MAIN_HEADER_HEIGHT: BASE_UNIT * 2.75,
  NAV_WIDTH: BASE_UNIT * 10,
};
