const Enumeration = {
  ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
  ACCESS_TOKEN_NOT_PROVIDED: 'ACCESS_TOKEN_NOT_PROVIDED',
  AUTH_ACCESS_TOKEN_REFRESH_FAILURE: 'AUTH_ACCESS_TOKEN_REFRESH_FAILURE',
  AUTH_REFRESH_TOKEN_COOKIE_NOT_FOUND: 'AUTH_REFRESH_TOKEN_COOKIE_NOT_FOUND',
  AUTH_REFRESH_TOKEN_DECRYPT_FAILED: 'AUTH_REFRESH_TOKEN_DECRYPT_FAILED',
  AUTH_REFRESH_TOKEN_VERSION_MISMATCH: 'AUTH_REFRESH_TOKEN_VERSION_MISMATCH',
  CAPTCHA_ERROR: 'CAPTCHA_ERROR',
  DATABASE_ERROR_OCCURRED: 'DATABASE_ERROR_OCCURRED',
  DATABASE_REQUEST_FAILED: 'DATABASE_REQUEST_FAILED',
  EMAIL_SEND_ERROR: 'EMAIL_SEND_ERROR',
  FAILED_LOGIN: 'FAILED_LOGIN',
  FAILED_LOGIN_PASSWORD_MISMATCH: 'FAILED_LOGIN:PASSWORD_MISMATCH',
  FAILED_LOGIN_USER_DELETED: 'FAILED_LOGIN:USER_DELETED',
  FAILED_LOGIN_USER_NOT_FOUND: 'FAILED_LOGIN:USER_NOT_FOUND',
  FAILED_TO_REVOKE_USER_REFRESH_TOKENS: 'FAILED_TO_REVOKE_USER_REFRESH_TOKENS',
  FORBIDDEN: 'FORBIDDEN',
  GENERIC: 'GENERIC',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  SELF_DELETE: 'SELF_DELETE',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  USER_DELETE_FAILED: 'USER_DELETE_FAILED',
  USER_DELETED: 'USER_DELETED',
  USER_PASSWORD_RESET_FAILED: 'USER_PASSWORD_RESET_FAILED',
  USER_PASSWORD_RESET_FAILED_TOKEN_EXPIRED:
    'USER_PASSWORD_RESET_FAILED:TOKEN_EXPIRED',
  USER_PASSWORD_RESET_FAILED_TOKEN_MISMATCH:
    'USER_PASSWORD_RESET_FAILED:TOKEN_MISMATCH',
  USER_REGISTER_FAILED: 'USER_REGISTER_FAILED',
  USER_REGISTER_FAILED_ALREADY_EXISTS: 'USER_REGISTER_FAILED:ALREADY_EXISTS',
  USER_SELF_FETCH_FAILED: 'USER_SELF_FETCH_FAILED',
  USER_SELF_FETCH_FAILED_USER_NOT_FOUND:
    'USER_SELF_FETCH_FAILED:USER_NOT_FOUND',
  USER_SELF_UPDATE_FAILED: 'USER_SELF_UPDATE_FAILED',
  USERS_FETCH_FAILED: 'USERS_FETCH_FAILED',
};

export { Enumeration };
