FROM node:12.13.0-alpine
LABEL \
  maintainer.name="Nate Clark" \
  maintainer.email="n8@n8io.com" \
  version=1.0.0

EXPOSE 3000

ENV \
  CI= \
  DEBUG= \
  NODE_ENV=development \
  YARN_CACHE_FOLDER=/yarn

RUN \
  mkdir -p $YARN_CACHE_FOLDER && \
  yarn global add lerna

WORKDIR /app

COPY ./entrypoint.sh ./

RUN chmod +x ./entrypoint.sh

ENTRYPOINT [ "./entrypoint.sh" ]

COPY \
  ./package.json \
  ./yarn.lock \
  ./

CMD ["yarn", "run", "-s", "start:ui"]
