version: '3.7'

services:
  db:
    container_name: db
    image: postgres:12.2-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=boilerplate-monorepo
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - data-db:/var/lib/postgresql/data
    restart: unless-stopped

  cache:
    command: ['redis-server', '--appendonly', 'yes']
    container_name: cache
    image: redis:5.0.7-alpine
    ports:
      - 6379:6379
    volumes:
      - data-cache:/data

  cache-ui:
    container_name: cache-ui
    image: rediscommander/redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:cache:6379
    ports:
      - 8081:8081

  email:
    container_name: email
    image: mailhog/mailhog
    restart: unless-stopped
    environment:
      MH_MAILDIR_PATH: /tmp
      MH_STORAGE: maildir
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - data-email:/tmp

  service:
    image: boilerplate-monorepo/service
    container_name: service
    restart: unless-stopped
    depends_on:
      - cache
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/boilerplate-monorepo
      DEBUG: '@boilerplate-monorepo/service*'
      EMAIL_SMTP_URL: smtp://user:password@email:1025
      REDIS_URL: redis://cache:6379
    ports:
      - 4000:4000
    volumes:
      - ./.ini:/app/.ini

  service-lambda:
    image: boilerplate-monorepo/service-lambda
    container_name: service-lambda
    restart: unless-stopped
    depends_on:
      - cache
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/boilerplate-monorepo
      DEBUG: '@boilerplate-monorepo/service*'
      EMAIL_SMTP_URL: smtp://user:password@email:1025
      HTTPS: 'false'
      LAMBDA_TASK_ROOT: '/var/task'
      PORT: 8080
      REDIS_URL: redis://cache:6379
      npm_package_name: '@boilerplate-monorepo/service'
      # SHOW_CONFIG: 'true'
    ports:
      - 4000:8080

volumes:
  data-cache:
  data-db:
  data-email:
  yarn-cache-service:
