import { values as rValues } from 'ramda';

const Enumeration = {
  ACCESS_TOKEN_EXPIRY: 'ACCESS_TOKEN_EXPIRY',
  ACCESS_TOKEN_SECRET: 'ACCESS_TOKEN_SECRET',
  CAPTCHA_SECRET: 'CAPTCHA_SECRET',
  CI: 'CI',
  DATABASE_MIGRATION_SCHEMA: 'DATABASE_MIGRATION_SCHEMA',
  DATABASE_MIGRATION_TABLE_NAME: 'DATABASE_MIGRATION_TABLE_NAME',
  DATABASE_SCHEMA: 'DB_SCHEMA',
  DATABASE_URL: 'DATABASE_URL',
  DATABASE_USE_SSL: 'DATABASE_USE_SSL',
  DEBUG: 'DEBUG',
  EMAIL_FROM_ADDRESS: 'EMAIL_FROM_ADDRESS',
  EMAIL_FROM_NAME: 'EMAIL_FROM_NAME',
  EMAIL_SMTP_TIMEOUT_SECONDS: 'EMAIL_SMTP_TIMEOUT_SECONDS',
  EMAIL_SMTP_URL: 'EMAIL_SMTP_URL',
  HTTPS: 'HTTPS',
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  REDIS_URL: 'REDIS_URL',
  REFRESH_TOKEN_EXPIRY: 'REFRESH_TOKEN_EXPIRY',
  REFRESH_TOKEN_SECRET: 'REFRESH_TOKEN_SECRET',
  SENTRY_DSN: 'SENTRY_DSN',
  SHOW_CONFIG: 'SHOW_CONFIG',
  UI_HOST_URI: 'UI_HOST_URI',
  /* eslint-disable camelcase */
  npm_package_name: 'npm_package_name',
  npm_package_version: 'npm_package_version',
  /* eslint-enable camelcase */
};

const values = rValues(Enumeration);

export { Enumeration, values };
