export const ErrorKeys = {
  DATE_FUTURE: 'DATE_FUTURE',
  DATE_PAST: 'DATE_PAST',
  INVALID_EMAIL: 'INVALID_EMAIL',
  RANGE_DATE: 'RANGE_DATE',
  RANGE_NUMERIC: 'RANGE_NUMERIC',
  RANGE_STRING_LENGTH: 'RANGE_STRING_LENGTH',
  RANGE_STRING_LENGTH_MAX: 'RANGE_STRING_LENGTH_MAX',
  RANGE_STRING_LENGTH_MIN: 'RANGE_STRING_LENGTH_MIN',
  REQUIRED: 'REQUIRED',
};
